version: '2.4'
services:
  db:
    image: db-mysql:1.0
    container_name: db
    build:
      context: ../backend/db/configuration
      dockerfile: Dockerfile-containerization
    networks:
      - spring-boot-application-net
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 5s
  backend:
    image: spring-boot-backend:1.0
    container_name: backend
    build:
      context: ../backend/spring-boot-backend
      dockerfile: Dockerfile
    networks:
      - spring-boot-application-net
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

networks:
  spring-boot-application-net: